weird req bug when specifying a patch version wildcard that doesnt exist for conda-forge::autoconf-
PackagesNotFoundError: The following packages are not available from current channels:
   - autoconf=2.69.0*

meanwhile, in the build log:

The following NEW packages will be INSTALLED:
    ...
    attr:                    2.5.2-h39aace5_0              conda-forge
    autoconf:                2.69-pl5321hd708f79_11        conda-forge
    automake:                1.16.5-pl5321ha770c72_0       conda-forge
    ...